import { useEffect } from 'react'
import { QueryClient, QueryClientProvider } from 'react-query'
import Head from 'next/head'

import '../styles/globals.css'

import Nav from '../components/Nav'
import useMetamask from '../hooks/useMetamask.js'
import useProvider from '../hooks/useProvider.js'


function MyApp({ Component, pageProps }) {
  const queryClient = new QueryClient()

  const provider = useProvider(state => state.provider)

  const connectProvider = useProvider(state => state.connectProvider)
  const connectSigner = useProvider(state => state.connectSigner)

  const haveMetamask = useMetamask(state => state.haveMetamask)
  const metamaskChainId = useMetamask(state => state.metamaskChainId)
  const metamaskAccount = useMetamask(state => state.metamaskAccount)

  const isMetamaskConnected = useMetamask(state => state.isMetamaskConnected)
  const isOnCorrectChain = useMetamask(state => state.isOnCorrectChain)

  const checkMetamask = useMetamask(state => state.checkMetamask)
  const checkMetamaskConnected = useMetamask(state => state.checkMetamaskConnected)
  const checkCorrectChain = useMetamask(state => state.checkCorrectChain)

  const handleChainChange = useMetamask(state => state.handleChainChange)
  const handleAccountChange = useMetamask(state => state.handleAccountChange)

  useEffect(() => {
    checkMetamask()
    checkMetamaskConnected()
  },[])

  useEffect(() => {
    // Handling User Disconnect
    checkMetamask()
    checkMetamaskConnected()
  },[metamaskAccount])

  useEffect(() => {
    if(isMetamaskConnected){
      handleChainChange()
      handleAccountChange()

      connectProvider()
    }
  },[isMetamaskConnected])

  useEffect(() => {
    connectSigner()
  }, [provider])

  useEffect(() => {
    if(metamaskChainId != null){
      checkCorrectChain()
    }
  },[metamaskChainId])


  if(!haveMetamask){
    return (
      <>
        <Nav />
        <div className="flex items-center justify-center w-full h-screen">
          <h1 className="text-3xl font-bold">Browser Doesn't Have Metamask :(</h1>
        </div>
      </>
    )
  }

  if(!isMetamaskConnected){
    return (
      <>
        <Nav />
        <div className="flex items-center justify-center w-full h-screen">
          <h1 className="text-3xl font-bold">Please Connect :(</h1>
        </div>
      </>
    )
  }

  if(!isOnCorrectChain){
    return (
      <>
        <Nav />
        <div className="flex items-center justify-center w-full h-screen">
          <h1 className="text-3xl font-bold">Please Connect To Polygon Mumbai :(</h1>
        </div>
      </>
    )
  }

  return(
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <QueryClientProvider client={queryClient}>
        <div className="w-full h-screen overflow-hidden">
          <Nav />
          <Component {...pageProps} />
        </div>
      </QueryClientProvider>
    </>
  ) 
}

export default MyApp
